// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7unf-a9XdJY4UKMpZMgKpPVFKZB51beU',
    appId: '1:389299327185:web:1872fe63e910e011c435f0',
    messagingSenderId: '389299327185',
    projectId: 'myharvest-2fe8e',
    authDomain: 'myharvest-2fe8e.firebaseapp.com',
    storageBucket: 'myharvest-2fe8e.appspot.com',
    measurementId: 'G-L7B9FWB0TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX0ApAMlX_S5d5PNTldq8GTQJzVq7ZMJg',
    appId: '1:389299327185:android:8dea2476302fcb94c435f0',
    messagingSenderId: '389299327185',
    projectId: 'myharvest-2fe8e',
    storageBucket: 'myharvest-2fe8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyiOXOwOHB8j5oSs5BNND6K18PPLT8bwg',
    appId: '1:389299327185:ios:d25473b3f5a8034dc435f0',
    messagingSenderId: '389299327185',
    projectId: 'myharvest-2fe8e',
    storageBucket: 'myharvest-2fe8e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyiOXOwOHB8j5oSs5BNND6K18PPLT8bwg',
    appId: '1:389299327185:ios:d25473b3f5a8034dc435f0',
    messagingSenderId: '389299327185',
    projectId: 'myharvest-2fe8e',
    storageBucket: 'myharvest-2fe8e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7unf-a9XdJY4UKMpZMgKpPVFKZB51beU',
    appId: '1:389299327185:web:47cfa11f5d7043fbc435f0',
    messagingSenderId: '389299327185',
    projectId: 'myharvest-2fe8e',
    authDomain: 'myharvest-2fe8e.firebaseapp.com',
    storageBucket: 'myharvest-2fe8e.appspot.com',
    measurementId: 'G-7YFFG2T0MP',
  );
}
